# Generated by Django 3.1 on 2020-10-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_sme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sme',
            old_name='username',
            new_name='brandname',
        ),
    ]
