# Generated by Django 3.1 on 2020-10-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20201023_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=62)),
                ('username', models.CharField(max_length=62)),
                ('email', models.CharField(max_length=62)),
                ('number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=62)),
                ('state', models.CharField(max_length=62)),
                ('city', models.CharField(max_length=62)),
                ('address', models.CharField(max_length=62)),
                ('occupation', models.CharField(max_length=62)),
                ('idno', models.CharField(max_length=62)),
                ('utility', models.CharField(max_length=62)),
                ('bvn', models.CharField(max_length=62)),
                ('whatsapp', models.CharField(max_length=62)),
                ('facebook', models.CharField(max_length=62)),
                ('instagram', models.CharField(max_length=62)),
                ('twitter', models.CharField(max_length=62)),
                ('linkedin', models.CharField(max_length=62)),
            ],
        ),
    ]
